### ISSUE TITLE
Choke with Multi is not working

### ISSUE THREAD

**Issue by DenkingOfficial** [mat1jaczyyy/outbreak#7] opened 2019-08-06 13:41 UTC
If I set choke to sample and instrument rack with Multi choke is not working

**Comment by Shqrp** [comment] 2019-08-06 21:22
Use apollo

**Comment by mat1jaczyyy** [comment] 2019-08-06 23:51
@TheLifeGamingYT why? If this is a bug in Outbreak, it should be fixed for people who use Outbreak. His use case is still inside sampling, choking in Drum Rack doesn't work properly

**Comment by mat1jaczyyy** [comment] 2019-08-07 04:11
Hey @DenkingOfficial, I can't reproduce this issue. My setup:
![image](https://user-images.githubusercontent.com/13300194/62594133-af4d3f00-b8d9-11e9-91fe-22ea29d15118.png)
I've checked in code and when a sample is choked, the device receives `176 120 0` which is a CC message. I've verified Multi forwards this message to the sample, and my samples are choked.

Can you update to the latest Multi and confirm if you still get the issue? If you do, show me your chain.

**Comment by mat1jaczyyy** [comment] 2019-08-26 01:15
Closing due to inactivity.

**Closed as completed by mat1jaczyyy** 2019-08-26 01:15 UTC
Labels: bug
